# Generated by Django 3.1.14 on 2024-09-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WiFi', 'WiFi'), ('Mini Bar', 'Mini Bar'), ('Swimming Pool', 'Swimming Pool'), ('Gym', 'Gym')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Smart TV', 'Smart TV'), ('Hair Dryer', 'Hair Dryer'), ('Air Conditioning', 'Air Conditioning'), ('Heating', 'Heating')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='view',
            field=models.CharField(choices=[('Lake', 'Lake View'), ('City', 'City View'), ('Mountain', 'Mountain View'), ('Jungle', 'Jungle View')], default='City', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Suite', 'Suite Room'), ('Family', 'Family Room')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='reservation.Amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='reservation.Facility'),
        ),
    ]
