# Generated by Django 3.1.14 on 2024-09-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20240908_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
